import React from 'react';
import { stats } from '../home/HomeStats';
// const stats = [
//   { label: 'leading brands delighting their customers', value: '8,000+' },
//   { label: 'of revenue generated by our partners', value: '$10M+' },
//   { label: 'community-conscious customers ordering directly', value: '120K+' },
// ];

const AboutMissionSection = () => {
  return (
    <div className='mx-auto -mt-12 max-w-7xl px-6 sm:mt-0 lg:px-8 xl:-mt-8'>
      <div className='mx-auto max-w-2xl lg:mx-0 lg:max-w-none'>
        <h2 className='max-w-2xl text-3xl font-bold tracking-tight text-gray-900 sm:text-5xl'>
          We are on a mission to help businesses grow
        </h2>
        <div className='mt-10 flex flex-col gap-x-8 gap-y-20 lg:flex-row'>
          <div className='lg:w-full lg:max-w-2xl lg:flex-auto'>
            <p className='text-xl leading-8 text-gray-600'>
              Across Bahrain and the world, we facilitate direct customer
              connections, eliminating intermediaries to ensure businesses
              retain their profits with sales income directly deposited into
              their bank accounts.
            </p>
            <div className='mt-10 max-w-xl text-base leading-7 text-gray-700'>
              <p>
                Experience the freedom to focus on business growth without
                unnecessary complexities.
              </p>
              <p className='mt-10'>
                With our streamlined approach, you can establish and strengthen
                customer relationships while optimizing your revenue flow for
                sustained success.
              </p>
            </div>
          </div>
          <div className='lg:flex lg:flex-auto lg:justify-center'>
            <dl className='w-64 space-y-8 xl:w-80'>
              {stats.slice(1, 4).map((stat) => (
                <div key={stat.name} className='flex flex-col-reverse gap-y-4'>
                  <dt className='text-base leading-7 text-gray-600'>
                    {stat.name}
                  </dt>
                  <dd className='text-5xl font-semibold tracking-tight text-gray-900'>
                    {stat.value}
                  </dd>
                </div>
              ))}
            </dl>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AboutMissionSection;
